export const BATCH_ADD = 'BATCH_ADD';
export const UPDATE_SONGS_DATA = 'UPDATE_SONGS_DATA';
export const UPDATE_RESERVE = 'UPDATE_RESERVE';
export const UPDATE_INDEX = 'UPDATE_INDEX';
export const UPDATE_MORE = 'UPDATE_MORE';

export default {
  BATCH_ADD,
  UPDATE_SONGS_DATA,
  UPDATE_MORE,
  UPDATE_INDEX,
  UPDATE_RESERVE,
};
