export const ADD = 'ADD';
export const BATCH_ADD = 'BATCH_ADD';
export const DELETE = 'DELETE';
export const UPDATE_FULLSCREEN = 'UPDATE_FULLSCREEN';
export const UPDATE_INDEX = 'UPDATE_INDEX';
export const UPDATE_SONG_AUDIOSRC = 'UPDATE_SONG_AUDIOSRC';
export const UPDATE_PLAYSTATE = 'UPDATE_PLAYSTATE';
export const UPDATE_SONG_CANPLAY = 'UPDATE_SONG_CANPLAY';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_SONGS = 'UPDATE_SONGS';
export const TOGGLE = 'TOGGLE';
export const CHOOSE = 'CHOOSE';
export const CLEAR = 'CLEAR';
export const UPDATE_MODE = 'UPDATE_MODE';
export const UPDATE_SONG_LYRIC = 'UPDATE_SONG_LYRIC';
export const UPDATE_WAY = 'UPDATE_WAY';

export default {
  ADD,
  BATCH_ADD,
  DELETE,
  UPDATE_FULLSCREEN,
  UPDATE_INDEX,
  UPDATE_SONG_AUDIOSRC,
  UPDATE_PLAYSTATE,
  UPDATE_SONG_CANPLAY,
  UPDATE_LOADING,
  UPDATE_SONGS,
  TOGGLE,
  CHOOSE,
  CLEAR,
  UPDATE_MODE,
  UPDATE_SONG_LYRIC,
  UPDATE_WAY,
};
