export const UPDATE_CONFIRM_SHOW = 'UPDATE_CONFIRM_SHOW';
export const UPDATE_CONFIRM_TITLE = 'UPDATE_CONFIRM_TITLE';
export const UPDATE_CONFIRM_EXECUTE = 'UPDATE_CONFIRM_EXECUTE';

export default {
  UPDATE_CONFIRM_SHOW,
  UPDATE_CONFIRM_TITLE,
  UPDATE_CONFIRM_EXECUTE,
};
